// <auto-generated />
using FAnsi.Discovery.TypeTranslation;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RGO.Data;
using RGO.DataAccess.Data;
using RGO.Utility;
using System;
using TypeGuesser;

namespace RGO.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            TypeTranslater dbTranslator = DatabaseHelper.Instance.GetTypeTranslator();


            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType(dbTranslator.GetSQLDBTypeForCSharpType(new DatabaseTypeRequest(typeof(string),450)));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType(dbTranslator.GetStringDataTypeWithUnlimitedWidth());

                    b.Property<string>("Name")
                        .HasColumnType(dbTranslator.GetSQLDBTypeForCSharpType(new DatabaseTypeRequest(typeof(string),256)))
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType(dbTranslator.GetSQLDBTypeForCSharpType(new DatabaseTypeRequest(typeof(string),256)))
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType(dbTranslator.GetStringDataTypeWithUnlimitedWidth());

                    b.Property<string>("ClaimValue")
                        .HasColumnType(dbTranslator.GetStringDataTypeWithUnlimitedWidth());

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType(dbTranslator.GetSQLDBTypeForCSharpType(new DatabaseTypeRequest(typeof(string),450)));

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType(dbTranslator.GetSQLDBTypeForCSharpType(new DatabaseTypeRequest(typeof(string),450)));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType(dbTranslator.GetStringDataTypeWithUnlimitedWidth());

                    b.Property<string>("Email")
                        .HasColumnType(dbTranslator.GetSQLDBTypeForCSharpType(new DatabaseTypeRequest(typeof(string),256)))
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType(dbTranslator.GetSQLDBTypeForCSharpType(new DatabaseTypeRequest(typeof(string),256)))
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType(dbTranslator.GetSQLDBTypeForCSharpType(new DatabaseTypeRequest(typeof(string),256)))
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType(dbTranslator.GetStringDataTypeWithUnlimitedWidth());

                    b.Property<string>("PhoneNumber")
                        .HasColumnType(dbTranslator.GetStringDataTypeWithUnlimitedWidth());

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType(dbTranslator.GetStringDataTypeWithUnlimitedWidth());

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType(dbTranslator.GetSQLDBTypeForCSharpType(new DatabaseTypeRequest(typeof(string),256)))
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType(dbTranslator.GetStringDataTypeWithUnlimitedWidth());

                    b.Property<string>("ClaimValue")
                        .HasColumnType(dbTranslator.GetStringDataTypeWithUnlimitedWidth());

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType(dbTranslator.GetSQLDBTypeForCSharpType(new DatabaseTypeRequest(typeof(string),450)));

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType(dbTranslator.GetStringDataTypeWithUnlimitedWidth());

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType(dbTranslator.GetSQLDBTypeForCSharpType(new DatabaseTypeRequest(typeof(string),450)));

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType(dbTranslator.GetSQLDBTypeForCSharpType(new DatabaseTypeRequest(typeof(string),450)));

                    b.Property<string>("RoleId")
                        .HasColumnType(dbTranslator.GetSQLDBTypeForCSharpType(new DatabaseTypeRequest(typeof(string),450)));

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType(dbTranslator.GetSQLDBTypeForCSharpType(new DatabaseTypeRequest(typeof(string),450)));

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType(dbTranslator.GetStringDataTypeWithUnlimitedWidth());

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
