// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RGO.DataAccess.Data;

#nullable disable

namespace RGO.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240207162129_Reseed1")]
    partial class Reseed1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RGO.Models.Group_Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Updated_By")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Group_Types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_By = "seed",
                            Created_Date = new DateTime(2024, 2, 7, 16, 21, 29, 147, DateTimeKind.Utc).AddTicks(9658),
                            Name = "Research Group"
                        },
                        new
                        {
                            Id = 2,
                            Created_By = "seed",
                            Created_Date = new DateTime(2024, 2, 7, 16, 21, 29, 147, DateTimeKind.Utc).AddTicks(9660),
                            Name = "Data Team"
                        });
                });

            modelBuilder.Entity("RGO.Models.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Group_TypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Updated_By")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Group_TypeId");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_By = "seed",
                            Created_Date = new DateTime(2024, 2, 7, 16, 21, 29, 147, DateTimeKind.Utc).AddTicks(9800),
                            Group_TypeId = 1,
                            Name = "Classification of Brain Images"
                        });
                });

            modelBuilder.Entity("RGO.Models.Models.Group_Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Updated_By")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Group_Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_By = "seed",
                            Created_Date = new DateTime(2024, 2, 7, 16, 21, 29, 147, DateTimeKind.Utc).AddTicks(9848),
                            Description = "Principal Investigator",
                            Name = "PI"
                        },
                        new
                        {
                            Id = 2,
                            Created_By = "seed",
                            Created_Date = new DateTime(2024, 2, 7, 16, 21, 29, 147, DateTimeKind.Utc).AddTicks(9850),
                            Description = "Research Assistant",
                            Name = "RA"
                        },
                        new
                        {
                            Id = 3,
                            Created_By = "seed",
                            Created_Date = new DateTime(2024, 2, 7, 16, 21, 29, 147, DateTimeKind.Utc).AddTicks(9852),
                            Description = "Ground Truther",
                            Name = "GT"
                        });
                });

            modelBuilder.Entity("RGO.Models.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrcId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Updated_By")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactInfo = "gerry@yahoo.ac.uk",
                            Created_By = "seed",
                            Created_Date = new DateTime(2024, 2, 7, 16, 21, 29, 147, DateTimeKind.Utc).AddTicks(9824),
                            Name = "Gerry Thomson",
                            Notes = "Academic Neuroradiologist",
                            OrcId = "123ABC"
                        },
                        new
                        {
                            Id = 2,
                            ContactInfo = "grant@yahoo.ac.uk",
                            Created_By = "seed",
                            Created_Date = new DateTime(2024, 2, 7, 16, 21, 29, 147, DateTimeKind.Utc).AddTicks(9826),
                            Name = "Grant Mair",
                            Notes = "Senior Clinical Lecturer in Neuroradiology",
                            OrcId = "456DEF"
                        },
                        new
                        {
                            Id = 3,
                            ContactInfo = "smarti@yahoo.ac.uk",
                            Created_By = "seed",
                            Created_Date = new DateTime(2024, 2, 7, 16, 21, 29, 147, DateTimeKind.Utc).AddTicks(9828),
                            Name = "Smarti Reel",
                            Notes = "Postdoctoral Researcher",
                            OrcId = ""
                        },
                        new
                        {
                            Id = 4,
                            ContactInfo = "kara@yahoo.ac.uk",
                            Created_By = "seed",
                            Created_Date = new DateTime(2024, 2, 7, 16, 21, 29, 147, DateTimeKind.Utc).AddTicks(9830),
                            Name = "Kara Moraw",
                            Notes = "EPCC Applications Developer",
                            OrcId = ""
                        });
                });

            modelBuilder.Entity("RGO.Models.Models.Person_Group_Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("End_Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Group_Id")
                        .HasColumnType("int");

                    b.Property<int>("Group_Role_Id")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Person_Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Start_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Updated_By")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Group_Id");

                    b.HasIndex("Group_Role_Id");

                    b.HasIndex("Person_Id");

                    b.ToTable("People_Group_Roles");
                });

            modelBuilder.Entity("RGO.Models.Models.RGOutput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Originating_GroupId")
                        .HasColumnType("int");

                    b.Property<int>("RGO_TypeId")
                        .HasColumnType("int");

                    b.Property<string>("Updated_By")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Originating_GroupId");

                    b.HasIndex("RGO_TypeId");

                    b.ToTable("RGOutputs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_By = "seed",
                            Created_Date = new DateTime(2024, 2, 7, 16, 21, 29, 147, DateTimeKind.Utc).AddTicks(9889),
                            Description = "Classifying the type of Brain Scans, done by Gerry and Grant",
                            Name = "MRI Classification Group Truth",
                            Originating_GroupId = 1,
                            RGO_TypeId = 1
                        });
                });

            modelBuilder.Entity("RGO.Models.RGO_Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Updated_By")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("RGO_Types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_By = "seed",
                            Created_Date = new DateTime(2024, 2, 7, 16, 21, 29, 147, DateTimeKind.Utc).AddTicks(9869),
                            Description = "Annotations that have been manually created or validated by a human expert",
                            Name = "Group Truth"
                        });
                });

            modelBuilder.Entity("RGO.Models.Models.Group", b =>
                {
                    b.HasOne("RGO.Models.Group_Type", "Group_Type")
                        .WithMany()
                        .HasForeignKey("Group_TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group_Type");
                });

            modelBuilder.Entity("RGO.Models.Models.Person_Group_Role", b =>
                {
                    b.HasOne("RGO.Models.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("Group_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RGO.Models.Models.Group_Role", "Group_Role")
                        .WithMany()
                        .HasForeignKey("Group_Role_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RGO.Models.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("Person_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Group_Role");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("RGO.Models.Models.RGOutput", b =>
                {
                    b.HasOne("RGO.Models.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("Originating_GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RGO.Models.RGO_Type", "RGO_Type")
                        .WithMany()
                        .HasForeignKey("RGO_TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("RGO_Type");
                });
#pragma warning restore 612, 618
        }
    }
}
