// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RGO.DataAccess.Data;

#nullable disable

namespace RGO.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240306155700_dbwork")]
    partial class dbwork
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RGO.Models.Evidence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Doi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EvidenceDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Evidence_TypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Updated_By")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Evidence_TypeId");

                    b.ToTable("Evidences");
                });

            modelBuilder.Entity("RGO.Models.Evidence_Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Updated_By")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Evidence_Types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_By = "seed",
                            Created_Date = new DateTime(2024, 3, 6, 15, 56, 59, 417, DateTimeKind.Utc).AddTicks(3683),
                            Description = "",
                            Name = "Peer Reviewed Publication"
                        },
                        new
                        {
                            Id = 2,
                            Created_By = "seed",
                            Created_Date = new DateTime(2024, 3, 6, 15, 56, 59, 417, DateTimeKind.Utc).AddTicks(3685),
                            Description = "",
                            Name = "Requested by another Research Project"
                        });
                });

            modelBuilder.Entity("RGO.Models.Group_Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Updated_By")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Group_Types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_By = "seed",
                            Created_Date = new DateTime(2024, 3, 6, 15, 56, 59, 417, DateTimeKind.Utc).AddTicks(3536),
                            Name = "Research Group"
                        },
                        new
                        {
                            Id = 2,
                            Created_By = "seed",
                            Created_Date = new DateTime(2024, 3, 6, 15, 56, 59, 417, DateTimeKind.Utc).AddTicks(3538),
                            Name = "Data Team"
                        });
                });

            modelBuilder.Entity("RGO.Models.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Group_TypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Updated_By")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Group_TypeId");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_By = "seed",
                            Created_Date = new DateTime(2024, 3, 6, 15, 56, 59, 417, DateTimeKind.Utc).AddTicks(3662),
                            Group_TypeId = 1,
                            Name = "Classification of Brain Images"
                        });
                });

            modelBuilder.Entity("RGO.Models.Models.RGO_Column", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Column_Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Column_Value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PK_Column_Order")
                        .HasColumnType("int");

                    b.Property<string>("Potentially_Disclosive")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RGO_RecordId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Updated_By")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RGO_RecordId");

                    b.ToTable("RGO_Columns");
                });

            modelBuilder.Entity("RGO.Models.Models.RGO_Column_Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PK_Column_Order")
                        .HasColumnType("int");

                    b.Property<string>("Potentially_Disclosive")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RGO_Dataset_TemplateId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Updated_By")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RGO_Dataset_TemplateId");

                    b.ToTable("RGO_Column_Templates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_By = "seed",
                            Created_Date = new DateTime(2024, 3, 6, 15, 56, 59, 417, DateTimeKind.Utc).AddTicks(4114),
                            Description = "Identifier of this image",
                            Name = "Image_Identifier",
                            PK_Column_Order = 1,
                            Potentially_Disclosive = "N",
                            RGO_Dataset_TemplateId = 1,
                            Type = "Int"
                        },
                        new
                        {
                            Id = 2,
                            Created_By = "seed",
                            Created_Date = new DateTime(2024, 3, 6, 15, 56, 59, 417, DateTimeKind.Utc).AddTicks(4122),
                            Description = "The ground truth that classifies the type of MRI this is e.g. T1, T2",
                            Name = "MRI_Classification",
                            Potentially_Disclosive = "N",
                            RGO_Dataset_TemplateId = 1,
                            Type = "Char"
                        },
                        new
                        {
                            Id = 3,
                            Created_By = "seed",
                            Created_Date = new DateTime(2024, 3, 6, 15, 56, 59, 417, DateTimeKind.Utc).AddTicks(4124),
                            Description = "An expert who generate this ground truth (1)",
                            Name = "Ground_Truther_1",
                            Potentially_Disclosive = "N",
                            RGO_Dataset_TemplateId = 1,
                            Type = "Int"
                        },
                        new
                        {
                            Id = 4,
                            Created_By = "seed",
                            Created_Date = new DateTime(2024, 3, 6, 15, 56, 59, 417, DateTimeKind.Utc).AddTicks(4126),
                            Description = "An expert who generate this ground truth (2)",
                            Name = "Ground_Truther_2",
                            Potentially_Disclosive = "N",
                            RGO_Dataset_TemplateId = 1,
                            Type = "Int"
                        },
                        new
                        {
                            Id = 5,
                            Created_By = "seed",
                            Created_Date = new DateTime(2024, 3, 6, 15, 56, 59, 417, DateTimeKind.Utc).AddTicks(4130),
                            Description = "The date on which this Ground Truth was finalised",
                            Name = "Date_GT_Recorded",
                            Potentially_Disclosive = "N",
                            RGO_Dataset_TemplateId = 1,
                            Type = "Date"
                        });
                });

            modelBuilder.Entity("RGO.Models.Models.RGO_Dataset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dataset_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dataset_Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RGO_Dataset_TemplateId")
                        .HasColumnType("int");

                    b.Property<string>("Updated_By")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RGO_Dataset_TemplateId");

                    b.ToTable("RGO_Datasets");
                });

            modelBuilder.Entity("RGO.Models.Models.RGO_Dataset_Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RGOutput_Id")
                        .HasColumnType("int");

                    b.Property<string>("Updated_By")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RGOutput_Id");

                    b.ToTable("RGO_Dataset_Templates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_By = "seed",
                            Created_Date = new DateTime(2024, 3, 6, 15, 56, 59, 417, DateTimeKind.Utc).AddTicks(4066),
                            Description = "Classifying the type of Brain Scans, done by Gerry and Grant",
                            Name = "MRI Classification Group Truth",
                            RGOutput_Id = 1
                        });
                });

            modelBuilder.Entity("RGO.Models.Models.RGO_Record", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RGO_DatasetId")
                        .HasColumnType("int");

                    b.Property<string>("Record_Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Updated_By")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RGO_DatasetId");

                    b.ToTable("RGO_Records");
                });

            modelBuilder.Entity("RGO.Models.Models.RGO_Record_Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Person_Record_Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RGO_RecordId")
                        .HasColumnType("int");

                    b.Property<string>("Updated_By")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("RGO_RecordId");

                    b.ToTable("RGO_Record_People");
                });

            modelBuilder.Entity("RGO.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrcId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Updated_By")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactInfo = "gerry@yahoo.ac.uk",
                            Created_By = "seed",
                            Created_Date = new DateTime(2024, 3, 6, 15, 56, 59, 417, DateTimeKind.Utc).AddTicks(3704),
                            Name = "Gerry Thomson",
                            Notes = "Academic Neuroradiologist",
                            OrcId = "123ABC"
                        },
                        new
                        {
                            Id = 2,
                            ContactInfo = "grant@yahoo.ac.uk",
                            Created_By = "seed",
                            Created_Date = new DateTime(2024, 3, 6, 15, 56, 59, 417, DateTimeKind.Utc).AddTicks(3707),
                            Name = "Grant Mair",
                            Notes = "Senior Clinical Lecturer in Neuroradiology",
                            OrcId = "456DEF"
                        },
                        new
                        {
                            Id = 3,
                            ContactInfo = "smarti@yahoo.ac.uk",
                            Created_By = "seed",
                            Created_Date = new DateTime(2024, 3, 6, 15, 56, 59, 417, DateTimeKind.Utc).AddTicks(3709),
                            Name = "Smarti Reel",
                            Notes = "Postdoctoral Researcher",
                            OrcId = ""
                        },
                        new
                        {
                            Id = 4,
                            ContactInfo = "kara@yahoo.ac.uk",
                            Created_By = "seed",
                            Created_Date = new DateTime(2024, 3, 6, 15, 56, 59, 417, DateTimeKind.Utc).AddTicks(3710),
                            Name = "Kara Moraw",
                            Notes = "EPCC Applications Developer",
                            OrcId = ""
                        });
                });

            modelBuilder.Entity("RGO.Models.RGO_Evidence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Evidence_Id")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RGOutput_Id")
                        .HasColumnType("int");

                    b.Property<string>("Updated_By")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Evidence_Id");

                    b.HasIndex("RGOutput_Id");

                    b.ToTable("RGO_Evidences");
                });

            modelBuilder.Entity("RGO.Models.RGO_Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Updated_By")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("RGO_Types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_By = "seed",
                            Created_Date = new DateTime(2024, 3, 6, 15, 56, 59, 417, DateTimeKind.Utc).AddTicks(3733),
                            Description = "Annotations that have been manually created or validated by a human expert",
                            Name = "Ground Truth"
                        });
                });

            modelBuilder.Entity("RGO.Models.RGOutput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Originating_GroupId")
                        .HasColumnType("int");

                    b.Property<int>("RGO_TypeId")
                        .HasColumnType("int");

                    b.Property<string>("Updated_By")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Originating_GroupId");

                    b.HasIndex("RGO_TypeId");

                    b.ToTable("RGOutputs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_By = "seed",
                            Created_Date = new DateTime(2024, 3, 6, 15, 56, 59, 417, DateTimeKind.Utc).AddTicks(3753),
                            Description = "Brain Scan Classifications",
                            Name = "MRI Classification Group Truth",
                            Originating_GroupId = 1,
                            RGO_TypeId = 1
                        });
                });

            modelBuilder.Entity("RGO.Models.Evidence", b =>
                {
                    b.HasOne("RGO.Models.Evidence_Type", "Evidence_Type")
                        .WithMany("Evidence")
                        .HasForeignKey("Evidence_TypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Evidence_Type");
                });

            modelBuilder.Entity("RGO.Models.Models.Group", b =>
                {
                    b.HasOne("RGO.Models.Group_Type", "Group_Type")
                        .WithMany("Group")
                        .HasForeignKey("Group_TypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Group_Type");
                });

            modelBuilder.Entity("RGO.Models.Models.RGO_Column", b =>
                {
                    b.HasOne("RGO.Models.Models.RGO_Record", "RGO_Record")
                        .WithMany()
                        .HasForeignKey("RGO_RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RGO_Record");
                });

            modelBuilder.Entity("RGO.Models.Models.RGO_Column_Template", b =>
                {
                    b.HasOne("RGO.Models.Models.RGO_Dataset_Template", "RGO_Dataset_Template")
                        .WithMany("RGO_Column_Template")
                        .HasForeignKey("RGO_Dataset_TemplateId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("RGO_Dataset_Template");
                });

            modelBuilder.Entity("RGO.Models.Models.RGO_Dataset", b =>
                {
                    b.HasOne("RGO.Models.Models.RGO_Dataset_Template", "RGO_Dataset_Template")
                        .WithMany()
                        .HasForeignKey("RGO_Dataset_TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RGO_Dataset_Template");
                });

            modelBuilder.Entity("RGO.Models.Models.RGO_Dataset_Template", b =>
                {
                    b.HasOne("RGO.Models.RGOutput", "RGOutput")
                        .WithMany("RGO_Dataset_Template")
                        .HasForeignKey("RGOutput_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("RGOutput");
                });

            modelBuilder.Entity("RGO.Models.Models.RGO_Record", b =>
                {
                    b.HasOne("RGO.Models.Models.RGO_Dataset", "RGO_Dataset")
                        .WithMany()
                        .HasForeignKey("RGO_DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RGO_Dataset");
                });

            modelBuilder.Entity("RGO.Models.Models.RGO_Record_Person", b =>
                {
                    b.HasOne("RGO.Models.Person", "Person")
                        .WithMany("RGO_Record_Person")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RGO.Models.Models.RGO_Record", "RGO_Record")
                        .WithMany("RGO_Record_Person")
                        .HasForeignKey("RGO_RecordId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("RGO_Record");
                });

            modelBuilder.Entity("RGO.Models.RGO_Evidence", b =>
                {
                    b.HasOne("RGO.Models.Evidence", "Evidence")
                        .WithMany("RGO_Evidence")
                        .HasForeignKey("Evidence_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RGO.Models.RGOutput", "RGOutput")
                        .WithMany()
                        .HasForeignKey("RGOutput_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evidence");

                    b.Navigation("RGOutput");
                });

            modelBuilder.Entity("RGO.Models.RGOutput", b =>
                {
                    b.HasOne("RGO.Models.Models.Group", "Group")
                        .WithMany("RGOutput")
                        .HasForeignKey("Originating_GroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RGO.Models.RGO_Type", "RGO_Type")
                        .WithMany("RGOutput")
                        .HasForeignKey("RGO_TypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("RGO_Type");
                });

            modelBuilder.Entity("RGO.Models.Evidence", b =>
                {
                    b.Navigation("RGO_Evidence");
                });

            modelBuilder.Entity("RGO.Models.Evidence_Type", b =>
                {
                    b.Navigation("Evidence");
                });

            modelBuilder.Entity("RGO.Models.Group_Type", b =>
                {
                    b.Navigation("Group");
                });

            modelBuilder.Entity("RGO.Models.Models.Group", b =>
                {
                    b.Navigation("RGOutput");
                });

            modelBuilder.Entity("RGO.Models.Models.RGO_Dataset_Template", b =>
                {
                    b.Navigation("RGO_Column_Template");
                });

            modelBuilder.Entity("RGO.Models.Models.RGO_Record", b =>
                {
                    b.Navigation("RGO_Record_Person");
                });

            modelBuilder.Entity("RGO.Models.Person", b =>
                {
                    b.Navigation("RGO_Record_Person");
                });

            modelBuilder.Entity("RGO.Models.RGO_Type", b =>
                {
                    b.Navigation("RGOutput");
                });

            modelBuilder.Entity("RGO.Models.RGOutput", b =>
                {
                    b.Navigation("RGO_Dataset_Template");
                });
#pragma warning restore 612, 618
        }
    }
}
